
server:
  port: 9090

spring:
  application:
    name: iaassistentchat

  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    location: classpath:db/migration
    baseline-on-migrate: true

  ai:
    openai:
      base-url: ${TOGETHER_API_URL}
      api-key: ${TOGETHER_API_KEY}
      chat:
        options:
          model: ${TOGETHER_API_CHAT_MODEL}
        completions-path: ${CHAT_COMPLETIONS_URL_PATH}
      embedding:
        embedding-path: ${TOGETHER_API_EMBEDDING_PATH}
        options:
          model: ${TOGETHER_API_EMBEDDING_MODEL} #text-embedding-ada-002

    vectorstore:
      pgvector:
        enabled: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

wikijs:
  base-url: ${WIKIJS_ADDRESS}
  token: ${WIKIJS_TOKEN}
  cookie-name: ${COOKIE_NAME}

login:
  level:
    root: INFO