services:
  postgres:
    image: pgvector/pgvector:pg16  # Usa imagem oficial com pgvector embutido
    container_name: wikichat-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
